import React, { useState, useEffect } from 'react';
import {
  Award,
  CheckCircle2,
  XCircle,
  Clock,
  RotateCcw,
  ArrowRight,
  Sparkles,
  HelpCircle,
  RefreshCw,
  Zap,
  BookOpen,
  Brain,
  Bot,
  Check,
  AlertCircle,
  Sliders,
  ChevronRight,
  Flame,
  MessageSquare,
} from 'lucide-react';
import { MODULE_QUIZZES } from '../data/quizzes';
import { useApp } from '../context/AppContext';
import { generateAiQuiz, askAiTutor } from '../services/aiService';
import { Quiz, QuizQuestion } from '../types';

interface QuizViewProps {
  initialQuizId?: string;
  navigate: (path: string) => void;
}

export const QuizView: React.FC<QuizViewProps> = ({ initialQuizId, navigate }) => {
  const { user, recordQuizAttempt, showToast, triggerConfetti } = useApp();

  const [activeQuizMeta, setActiveQuizMeta] = useState<Quiz | null>(null);
  const [activeQuestions, setActiveQuestions] = useState<QuizQuestion[]>([]);
  const [isGeneratingAi, setIsGeneratingAi] = useState<boolean>(false);
  const [aiSource, setAiSource] = useState<'gemini' | 'fallback' | 'base'>('base');
  const [aiModel, setAiModel] = useState<string>('gemini-3.7-flash');

  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [selectedAnswers, setSelectedAnswers] = useState<Record<string, number>>({});
  const [isSubmitted, setIsSubmitted] = useState(false);

  // AI Tutor Deep Dive on Results Screen
  const [activeExplainQ, setActiveExplainQ] = useState<QuizQuestion | null>(null);
  const [explainAiText, setExplainAiText] = useState<string>('');
  const [isExplainingAi, setIsExplainingAi] = useState<boolean>(false);

  // Custom AI Quiz Generator Form State
  const [customTopicInput, setCustomTopicInput] = useState<string>('');
  const [customDifficulty, setCustomDifficulty] = useState<'Easy' | 'Medium' | 'Hard'>('Medium');
  const [isCustomAiModalOpen, setIsCustomAiModalOpen] = useState<boolean>(false);

  // Initialize initial quiz if passed via props
  useEffect(() => {
    if (initialQuizId) {
      const found = MODULE_QUIZZES.find((q) => q.id === initialQuizId);
      if (found) {
        startQuizWithFreshAiQuestions(found);
      }
    }
  }, [initialQuizId]);

  // Load fresh Gemini AI questions for a quiz
  const startQuizWithFreshAiQuestions = async (quiz: Quiz, customTopic?: string) => {
    setActiveQuizMeta(quiz);
    setCurrentQuestionIndex(0);
    setSelectedAnswers({});
    setIsSubmitted(false);
    setIsGeneratingAi(true);
    setActiveExplainQ(null);
    setExplainAiText('');

    try {
      const excludeTitles = activeQuestions.map((q) => q.question);
      const res = await generateAiQuiz({
        topicTitle: customTopic || quiz.title,
        moduleId: quiz.moduleId,
        difficulty: quiz.id === 'q_1' || quiz.id === 'q_2' ? 'Easy' : quiz.id === 'q_9' || quiz.id === 'q_10' ? 'Hard' : 'Medium',
        count: 5,
        excludeQuestions: excludeTitles,
        customTopic,
      });

      if (res && res.questions && res.questions.length > 0) {
        setActiveQuestions(res.questions);
        setAiSource(res.source === 'gemini' ? 'gemini' : 'fallback');
        if (res.model) setAiModel(res.model);
        if (res.source === 'gemini') {
          showToast('success', 'Fresh AI Questions Ready!', 'Generated unique questions powered by Gemini AI.');
        } else {
          showToast('info', 'Quiz Ready!', 'Loaded fresh randomized SQL questions.');
        }
      } else {
        // Fallback to base questions
        setActiveQuestions(quiz.questions);
        setAiSource('base');
      }
    } catch (err: any) {
      console.warn('Could not generate AI quiz questions, using module defaults:', err);
      setActiveQuestions(quiz.questions);
      setAiSource('base');
    } finally {
      setIsGeneratingAi(false);
    }
  };

  // Launch custom AI topic quiz
  const handleLaunchCustomAiQuiz = async () => {
    if (!customTopicInput.trim()) {
      showToast('error', 'Topic Required', 'Please enter a SQL topic to generate your quiz.');
      return;
    }

    const customQuiz: Quiz = {
      id: `custom_ai_${Date.now()}`,
      moduleId: 'custom',
      title: `AI Custom Quiz: ${customTopicInput.trim()}`,
      description: `Custom interactive SQL assessment generated by Gemini AI for topic: "${customTopicInput.trim()}" (${customDifficulty} difficulty).`,
      timeLimitMinutes: 10,
      xpReward: customDifficulty === 'Hard' ? 50 : customDifficulty === 'Medium' ? 40 : 30,
      questions: [],
    };

    setIsCustomAiModalOpen(false);
    await startQuizWithFreshAiQuestions(customQuiz, customTopicInput.trim());
  };

  const handleSelectAnswer = (questionId: string, optionIdx: number) => {
    if (isSubmitted) return;
    setSelectedAnswers((prev) => ({ ...prev, [questionId]: optionIdx }));
  };

  const calculateScore = () => {
    if (!activeQuestions || activeQuestions.length === 0) return 0;
    let correct = 0;
    activeQuestions.forEach((q) => {
      if (selectedAnswers[q.id] === q.correctAnswerIndex) {
        correct++;
      }
    });
    return Math.round((correct / activeQuestions.length) * 100);
  };

  const handleSubmitQuiz = () => {
    if (!activeQuizMeta || activeQuestions.length === 0) return;
    setIsSubmitted(true);
    const score = calculateScore();
    recordQuizAttempt(activeQuizMeta.id, score);

    if (score >= 80) {
      triggerConfetti();
      showToast('success', `Quiz Passed with ${score}%!`, `Great job! You earned +${activeQuizMeta.xpReward} XP.`);
    } else {
      showToast('info', `Quiz Completed: ${score}%`, `Review the answers and AI explanations below.`);
    }
  };

  // Ask AI Tutor for instant in-depth explanation
  const handleAskAiExplanation = async (question: QuizQuestion) => {
    setActiveExplainQ(question);
    setIsExplainingAi(true);
    setExplainAiText('');

    try {
      const userSelectedOpt =
        selectedAnswers[question.id] !== undefined
          ? question.options[selectedAnswers[question.id]]
          : 'None selected';
      const correctOpt = question.options[question.correctAnswerIndex];

      const res = await askAiTutor({
        prompt: `Explain why the correct answer to this SQL question is "${correctOpt}" and why "${userSelectedOpt}" was selected/incorrect. Break down the core database mechanism clearly.`,
        mode: 'explain',
        context: {
          problemTitle: question.question,
          userQuery: question.codeSnippet || '',
        },
      });

      setExplainAiText(res.text);
    } catch (err: any) {
      setExplainAiText('Unable to reach AI explanation service. Please check the built-in explanation above.');
    } finally {
      setIsExplainingAi(false);
    }
  };

  // 1. ACTIVE QUIZ VIEW (IN PROGRESS OR RESULTS)
  if (activeQuizMeta) {
    const currentQ = activeQuestions[currentQuestionIndex];
    const score = isSubmitted ? calculateScore() : 0;

    return (
      <div id="active-quiz-container" className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-6">
        {/* Top Navigation & Status Bar */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-4 border-b border-slate-200 dark:border-slate-800">
          <button
            id="btn-back-to-catalog"
            onClick={() => {
              setActiveQuizMeta(null);
              setActiveQuestions([]);
            }}
            className="text-xs font-semibold text-slate-500 hover:text-slate-900 dark:hover:text-white flex items-center gap-1.5 transition-colors self-start"
          >
            ← Back to Quiz Catalog
          </button>

          <div className="flex items-center gap-2 flex-wrap">
            <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-[11px] font-bold bg-indigo-50 dark:bg-indigo-950/60 text-indigo-700 dark:text-indigo-300 border border-indigo-200 dark:border-indigo-800">
              <Sparkles className="w-3 h-3 text-indigo-500 animate-pulse" />
              {aiSource === 'gemini' ? '✨ Gemini AI Dynamic Questions' : '⚡ Fresh Changing Questions'}
            </span>

            {/* Regenerate Button */}
            {!isSubmitted && (
              <button
                id="btn-regenerate-ai-questions"
                disabled={isGeneratingAi}
                onClick={() => startQuizWithFreshAiQuestions(activeQuizMeta)}
                className="px-3 py-1 rounded-full text-[11px] font-bold bg-sky-50 dark:bg-sky-950/60 text-sky-700 dark:text-sky-300 border border-sky-200 dark:border-sky-800 hover:bg-sky-100 flex items-center gap-1 transition-all disabled:opacity-50"
                title="Fetch a completely new set of unique questions using Gemini API"
              >
                <RefreshCw className={`w-3 h-3 ${isGeneratingAi ? 'animate-spin' : ''}`} />
                {isGeneratingAi ? 'Generating...' : 'New Questions (AI)'}
              </button>
            )}
          </div>
        </div>

        {/* LOADING STATE WHEN GEMINI GENERATES FRESH QUESTIONS */}
        {isGeneratingAi ? (
          <div
            id="quiz-ai-loading"
            className="border border-slate-200 dark:border-slate-800 rounded-3xl p-10 bg-white dark:bg-slate-900 shadow-sm text-center space-y-6"
          >
            <div className="w-16 h-16 rounded-2xl mx-auto bg-gradient-to-tr from-sky-500 via-indigo-500 to-purple-600 flex items-center justify-center text-white shadow-lg shadow-indigo-500/25 animate-pulse">
              <Brain className="w-8 h-8 animate-bounce" />
            </div>
            <div className="space-y-2 max-w-md mx-auto">
              <h3 className="text-xl font-black text-slate-900 dark:text-white">
                Generating Fresh Questions with Gemini AI
              </h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Crafting unique, challenging SQL multiple-choice, syntax, and query prediction problems for{' '}
                <span className="font-bold text-indigo-600 dark:text-indigo-400">{activeQuizMeta.title}</span>...
              </p>
            </div>
            <div className="flex items-center justify-center gap-2 text-xs font-semibold text-indigo-600 dark:text-indigo-400">
              <Sparkles className="w-4 h-4 animate-spin" /> Powered by Gemini API
            </div>
          </div>
        ) : !isSubmitted && currentQ ? (
          /* ACTIVE QUESTION CARD */
          <div
            id="quiz-active-question-card"
            className="border border-slate-200 dark:border-slate-800 rounded-3xl p-6 sm:p-8 bg-white dark:bg-slate-900 shadow-xs space-y-6"
          >
            {/* Header / Progress */}
            <div className="flex items-center justify-between text-xs pb-3 border-b border-slate-100 dark:border-slate-800">
              <div className="flex items-center gap-2">
                <span className="font-bold text-slate-600 dark:text-slate-300">
                  Question {currentQuestionIndex + 1} of {activeQuestions.length}
                </span>
                <span className="px-2 py-0.5 rounded-md text-[10px] font-bold uppercase tracking-wider bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300">
                  {currentQ.type.replace('_', ' ')}
                </span>
                <span className="px-2 py-0.5 rounded-md text-[10px] font-bold bg-sky-100 dark:bg-sky-950 text-sky-700 dark:text-sky-300">
                  {currentQ.topic}
                </span>
              </div>
              <span className="font-semibold text-amber-500 flex items-center gap-1">
                <Sparkles className="w-3.5 h-3.5" /> +{activeQuizMeta.xpReward} XP Reward
              </span>
            </div>

            {/* Question Text */}
            <h3 className="text-lg sm:text-xl font-bold text-slate-900 dark:text-white leading-relaxed">
              {currentQ.question}
            </h3>

            {/* Code Snippet if present */}
            {currentQ.codeSnippet && (
              <div className="space-y-1">
                <div className="text-[11px] font-semibold text-slate-400 dark:text-slate-500 uppercase tracking-wider">
                  SQL Query Reference:
                </div>
                <pre className="p-4 rounded-2xl bg-slate-950 text-sky-300 font-mono text-xs overflow-x-auto border border-slate-800 leading-relaxed shadow-inner">
                  {currentQ.codeSnippet}
                </pre>
              </div>
            )}

            {/* Multiple Choice Options */}
            <div className="space-y-3 pt-2">
              {currentQ.options.map((option, optIdx) => {
                const isSelected = selectedAnswers[currentQ.id] === optIdx;
                return (
                  <button
                    key={optIdx}
                    id={`quiz-option-${currentQ.id}-${optIdx}`}
                    onClick={() => handleSelectAnswer(currentQ.id, optIdx)}
                    className={`w-full p-4 rounded-2xl text-left text-xs font-medium border transition-all flex items-center justify-between gap-3 ${
                      isSelected
                        ? 'bg-sky-50/90 dark:bg-sky-950/80 border-sky-500 text-sky-950 dark:text-sky-100 font-bold shadow-sm ring-1 ring-sky-500'
                        : 'bg-slate-50/50 dark:bg-slate-950/50 border-slate-200 dark:border-slate-800 text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800/60'
                    }`}
                  >
                    <div className="flex items-center gap-3">
                      <span
                        className={`w-6 h-6 rounded-lg text-xs font-bold flex items-center justify-center ${
                          isSelected
                            ? 'bg-sky-600 text-white'
                            : 'bg-slate-200 dark:bg-slate-800 text-slate-600 dark:text-slate-400'
                        }`}
                      >
                        {String.fromCharCode(65 + optIdx)}
                      </span>
                      <span>{option}</span>
                    </div>
                    <span
                      className={`w-4 h-4 rounded-full border flex items-center justify-center shrink-0 ${
                        isSelected ? 'border-sky-500 bg-sky-500 text-white' : 'border-slate-400'
                      }`}
                    >
                      {isSelected && <span className="w-1.5 h-1.5 rounded-full bg-white"></span>}
                    </span>
                  </button>
                );
              })}
            </div>

            {/* Bottom Actions & Pagination */}
            <div className="flex items-center justify-between pt-4 border-t border-slate-100 dark:border-slate-800">
              <button
                id="btn-prev-question"
                onClick={() => setCurrentQuestionIndex((i) => Math.max(0, i - 1))}
                disabled={currentQuestionIndex === 0}
                className="px-4 py-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 font-semibold text-xs disabled:opacity-40 hover:bg-slate-200 transition-colors"
              >
                Previous
              </button>

              <div className="text-xs font-semibold text-slate-400">
                Answered {Object.keys(selectedAnswers).length} of {activeQuestions.length}
              </div>

              {currentQuestionIndex < activeQuestions.length - 1 ? (
                <button
                  id="btn-next-question"
                  onClick={() => setCurrentQuestionIndex((i) => Math.min(activeQuestions.length - 1, i + 1))}
                  className="px-6 py-2.5 rounded-xl bg-sky-600 hover:bg-sky-700 text-white font-semibold text-xs shadow-xs transition-colors"
                >
                  Next Question
                </button>
              ) : (
                <button
                  id="btn-submit-assessment"
                  onClick={handleSubmitQuiz}
                  disabled={Object.keys(selectedAnswers).length < activeQuestions.length}
                  className="px-6 py-2.5 rounded-xl bg-gradient-to-r from-emerald-500 to-teal-600 hover:from-emerald-600 hover:to-teal-700 text-white font-bold text-xs shadow-md transition-all disabled:opacity-50"
                >
                  Submit Assessment
                </button>
              )}
            </div>
          </div>
        ) : (
          /* ASSESSMENT RESULTS & AI REVIEW VIEW */
          <div
            id="quiz-results-card"
            className="border border-slate-200 dark:border-slate-800 rounded-3xl p-6 sm:p-8 bg-white dark:bg-slate-900 shadow-xs space-y-8"
          >
            <div className="text-center space-y-3 pb-6 border-b border-slate-200 dark:border-slate-800">
              <div
                className={`w-16 h-16 rounded-2xl mx-auto flex items-center justify-center text-white shadow-lg ${
                  score >= 80
                    ? 'bg-gradient-to-tr from-emerald-500 to-teal-600 shadow-emerald-500/20'
                    : 'bg-gradient-to-tr from-sky-500 to-indigo-600 shadow-sky-500/20'
                }`}
              >
                <Award className="w-8 h-8" />
              </div>
              <h2 className="text-2xl font-black text-slate-900 dark:text-white">Assessment Complete!</h2>
              <div
                className={`text-5xl font-black ${
                  score >= 80 ? 'text-emerald-600 dark:text-emerald-400' : 'text-sky-600 dark:text-sky-400'
                }`}
              >
                {score}%
              </div>
              <p className="text-xs text-slate-500 dark:text-slate-400 max-w-md mx-auto">
                {score >= 80
                  ? 'Mastery demonstrated! Outstanding retention on this SQL topic.'
                  : 'Good attempt! Review the detailed answers and explanations below to reinforce your knowledge.'}
              </p>
            </div>

            {/* Questions Detailed Breakdown */}
            <div className="space-y-4">
              <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400">
                Detailed Question Analysis ({activeQuestions.length} Questions)
              </h4>

              {activeQuestions.map((q, idx) => {
                const userAns = selectedAnswers[q.id];
                const isCorrect = userAns === q.correctAnswerIndex;
                return (
                  <div
                    key={q.id}
                    className={`p-5 rounded-2xl border text-xs space-y-3 transition-all ${
                      isCorrect
                        ? 'bg-emerald-50/40 dark:bg-emerald-950/20 border-emerald-200 dark:border-emerald-800'
                        : 'bg-rose-50/40 dark:bg-rose-950/20 border-rose-200 dark:border-rose-800'
                    }`}
                  >
                    <div className="flex items-start justify-between gap-3 font-bold">
                      <span className="text-slate-900 dark:text-white leading-relaxed">
                        {idx + 1}. {q.question}
                      </span>
                      {isCorrect ? (
                        <span className="flex items-center gap-1 text-emerald-600 dark:text-emerald-400 font-bold shrink-0">
                          <CheckCircle2 className="w-4 h-4" /> Correct
                        </span>
                      ) : (
                        <span className="flex items-center gap-1 text-rose-600 dark:text-rose-400 font-bold shrink-0">
                          <XCircle className="w-4 h-4" /> Incorrect
                        </span>
                      )}
                    </div>

                    {q.codeSnippet && (
                      <pre className="p-3 rounded-xl bg-slate-950 text-sky-300 font-mono text-[11px] overflow-x-auto border border-slate-800">
                        {q.codeSnippet}
                      </pre>
                    )}

                    <div className="space-y-1.5 pt-1">
                      <div className="text-slate-700 dark:text-slate-300">
                        <span className="font-bold text-slate-900 dark:text-white">Your Answer: </span>
                        <span className={isCorrect ? 'text-emerald-700 dark:text-emerald-400 font-bold' : 'text-rose-700 dark:text-rose-400 line-through'}>
                          {userAns !== undefined ? q.options[userAns] : 'Not Answered'}
                        </span>
                      </div>

                      {!isCorrect && (
                        <div className="text-emerald-700 dark:text-emerald-400">
                          <span className="font-bold">Correct Answer: </span>
                          <span className="font-bold">{q.options[q.correctAnswerIndex]}</span>
                        </div>
                      )}
                    </div>

                    <div className="p-3 rounded-xl bg-white/70 dark:bg-slate-900/70 border border-slate-200/60 dark:border-slate-800/60 text-slate-600 dark:text-slate-300 text-[11px] leading-relaxed">
                      <span className="font-bold text-slate-800 dark:text-slate-200">Explanation: </span>
                      {q.explanation}
                    </div>

                    {/* Ask AI Tutor Button */}
                    <button
                      id={`btn-ask-ai-q-${q.id}`}
                      onClick={() => handleAskAiExplanation(q)}
                      className="inline-flex items-center gap-1.5 text-[11px] font-bold text-indigo-600 dark:text-indigo-400 hover:text-indigo-800 dark:hover:text-indigo-200 transition-colors pt-1"
                    >
                      <Bot className="w-3.5 h-3.5" /> Ask AI Tutor to Explain this Deeply →
                    </button>
                  </div>
                );
              })}
            </div>

            {/* AI Explanation Modal / Box if triggered */}
            {activeExplainQ && (
              <div
                id="ai-tutor-explanation-box"
                className="p-6 rounded-3xl border border-indigo-200 dark:border-indigo-800 bg-indigo-50/50 dark:bg-indigo-950/30 space-y-3"
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2 font-bold text-xs text-indigo-900 dark:text-indigo-200">
                    <Sparkles className="w-4 h-4 text-indigo-500" />
                    AI SQL Tutor Deep-Dive on: "{activeExplainQ.question.slice(0, 60)}..."
                  </div>
                  <button
                    onClick={() => setActiveExplainQ(null)}
                    className="text-xs font-semibold text-indigo-600 hover:text-indigo-900 dark:text-indigo-300"
                  >
                    Close
                  </button>
                </div>

                {isExplainingAi ? (
                  <div className="flex items-center gap-2 text-xs text-indigo-600 dark:text-indigo-400 py-4 font-semibold">
                    <Sparkles className="w-4 h-4 animate-spin" /> Gemini AI is analyzing the question logic...
                  </div>
                ) : (
                  <div className="text-xs text-slate-700 dark:text-slate-300 whitespace-pre-wrap leading-relaxed">
                    {explainAiText}
                  </div>
                )}
              </div>
            )}

            {/* Action Bar (Retake with New Questions, Done) */}
            <div className="flex flex-col sm:flex-row items-center justify-between gap-3 pt-6 border-t border-slate-200 dark:border-slate-800">
              <button
                id="btn-retake-new-ai-questions"
                onClick={() => startQuizWithFreshAiQuestions(activeQuizMeta)}
                className="w-full sm:w-auto px-5 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs flex items-center justify-center gap-2 shadow-xs transition-colors"
              >
                <RefreshCw className="w-4 h-4" /> Retake with New AI Questions (Changes Every Time)
              </button>

              <button
                id="btn-quiz-done"
                onClick={() => {
                  setActiveQuizMeta(null);
                  setActiveQuestions([]);
                }}
                className="w-full sm:w-auto px-6 py-2.5 rounded-xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-200 font-semibold text-xs transition-colors"
              >
                Done / Back to Catalog
              </button>
            </div>
          </div>
        )}
      </div>
    );
  }

  // 2. QUIZ CATALOG VIEW (ALL MODULES + CUSTOM AI GENERATOR)
  return (
    <div id="quiz-catalog-view" className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="px-3 py-1 rounded-full text-xs font-bold bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300 flex items-center gap-1 border border-indigo-200 dark:border-indigo-800">
              <Sparkles className="w-3.5 h-3.5 text-indigo-500" /> Powered by Gemini API
            </span>
          </div>
          <h1 className="text-3xl font-black text-slate-900 dark:text-white mt-2 flex items-center gap-2">
            <Award className="w-8 h-8 text-indigo-500" /> SQL Skill Assessments & Quizzes
          </h1>
          <p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400 mt-1 max-w-2xl">
            Questions change dynamically on every single attempt using the Gemini API. Test and validate your query logic, operator precedence, syntax rules, and output predictions.
          </p>
        </div>

        {/* Custom AI Quiz Button */}
        <button
          id="btn-open-custom-ai-quiz-modal"
          onClick={() => setIsCustomAiModalOpen(true)}
          className="px-5 py-3 rounded-2xl bg-gradient-to-r from-indigo-600 via-sky-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700 text-white font-bold text-xs shadow-lg shadow-indigo-500/20 flex items-center gap-2 transition-all shrink-0 self-start md:self-auto"
        >
          <Brain className="w-4 h-4" /> ✨ Custom AI Topic Quiz Generator
        </button>
      </div>

      {/* CUSTOM AI QUIZ GENERATOR BANNER / MODAL */}
      {isCustomAiModalOpen && (
        <div
          id="custom-ai-quiz-modal"
          className="border-2 border-indigo-500/40 rounded-3xl p-6 sm:p-8 bg-gradient-to-br from-indigo-50/80 via-sky-50/50 to-white dark:from-indigo-950/40 dark:via-slate-900 dark:to-slate-900 shadow-xl space-y-6"
        >
          <div className="flex items-center justify-between pb-3 border-b border-indigo-100 dark:border-indigo-900">
            <div className="flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
              <h3 className="font-black text-base text-slate-900 dark:text-white">
                Generate a Custom AI SQL Quiz with Gemini
              </h3>
            </div>
            <button
              onClick={() => setIsCustomAiModalOpen(false)}
              className="text-xs font-bold text-slate-400 hover:text-slate-600 dark:hover:text-white"
            >
              ✕ Cancel
            </button>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="md:col-span-2 space-y-2">
              <label className="text-xs font-bold text-slate-700 dark:text-slate-300">
                SQL Topic or Scenario (e.g. Recursive CTEs, Window Functions, Indexing, Joins vs Subqueries):
              </label>
              <input
                type="text"
                id="input-custom-quiz-topic"
                value={customTopicInput}
                onChange={(e) => setCustomTopicInput(e.target.value)}
                placeholder="e.g. DENSE_RANK() vs RANK(), ACID Transactions, Left Outer Joins"
                className="w-full p-3.5 rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-white text-xs focus:ring-2 focus:ring-indigo-500 outline-hidden"
              />
            </div>

            <div className="space-y-2">
              <label className="text-xs font-bold text-slate-700 dark:text-slate-300">Difficulty Level:</label>
              <div className="grid grid-cols-3 gap-2">
                {(['Easy', 'Medium', 'Hard'] as const).map((diff) => (
                  <button
                    key={diff}
                    type="button"
                    onClick={() => setCustomDifficulty(diff)}
                    className={`py-3 rounded-xl text-xs font-bold border transition-all ${
                      customDifficulty === diff
                        ? 'bg-indigo-600 text-white border-indigo-600 shadow-xs'
                        : 'bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-300 border-slate-200 dark:border-slate-700 hover:bg-slate-50'
                    }`}
                  >
                    {diff}
                  </button>
                ))}
              </div>
            </div>
          </div>

          <div className="flex flex-wrap items-center justify-between gap-3 pt-2">
            <div className="flex items-center gap-2 text-xs text-slate-500">
              <span>Quick suggestions:</span>
              {['Window Functions', 'Recursive CTEs', '3NF Normalization', 'NULL Handling'].map((sug) => (
                <button
                  key={sug}
                  type="button"
                  onClick={() => setCustomTopicInput(sug)}
                  className="px-2.5 py-1 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-[11px] font-semibold text-slate-700 dark:text-slate-300 hover:border-indigo-400"
                >
                  {sug}
                </button>
              ))}
            </div>

            <button
              id="btn-launch-ai-custom-quiz"
              onClick={handleLaunchCustomAiQuiz}
              className="px-6 py-3 rounded-xl bg-gradient-to-r from-indigo-600 to-sky-600 hover:from-indigo-700 hover:to-sky-700 text-white font-bold text-xs shadow-md flex items-center gap-2"
            >
              <Sparkles className="w-4 h-4" /> Generate & Start Quiz Now
            </button>
          </div>
        </div>
      )}

      {/* QUIZ MODULE CARDS GRID */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {MODULE_QUIZZES.map((quiz) => {
          const attempt = user.completedQuizzes.find((q) => q.quizId === quiz.id);
          return (
            <div
              key={quiz.id}
              id={`quiz-card-${quiz.id}`}
              onClick={() => startQuizWithFreshAiQuestions(quiz)}
              className="p-6 rounded-3xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 hover:border-indigo-400 dark:hover:border-indigo-600 hover:shadow-xl transition-all cursor-pointer space-y-4 group flex flex-col justify-between"
            >
              <div className="space-y-3">
                <div className="flex items-center justify-between text-xs">
                  <span className="inline-flex items-center gap-1 font-bold text-indigo-600 dark:text-indigo-400">
                    <Sparkles className="w-3.5 h-3.5 text-indigo-500" /> Dynamic AI Questions
                  </span>
                  <span className="font-bold text-amber-500">+{quiz.xpReward} XP</span>
                </div>

                <h3 className="font-bold text-base text-slate-900 dark:text-white group-hover:text-indigo-500 dark:group-hover:text-indigo-400 transition-colors">
                  {quiz.title}
                </h3>

                <p className="text-xs text-slate-500 dark:text-slate-400 line-clamp-2 leading-relaxed">
                  {quiz.description}
                </p>
              </div>

              <div className="pt-4 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between text-xs">
                {attempt ? (
                  <span className="font-bold text-emerald-600 dark:text-emerald-400 flex items-center gap-1">
                    <CheckCircle2 className="w-3.5 h-3.5" /> Best Score: {attempt.score}%
                  </span>
                ) : (
                  <span className="text-slate-400 font-medium">Ready to Attempt</span>
                )}
                <span className="font-bold text-indigo-600 dark:text-indigo-400 flex items-center gap-1 group-hover:translate-x-1 transition-transform">
                  Take AI Quiz <ArrowRight className="w-3.5 h-3.5" />
                </span>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
