import { SqlProject } from '../types';

export const SQL_PROJECTS: SqlProject[] = [
  {
    id: 'proj_1',
    title: 'University Student Management System',
    category: 'Education',
    difficulty: 'Medium',
    estimatedHours: 4,
    problemStatement: 'Design and query a comprehensive university academic administration system to track students, professors, departmental budgets, and semester enrollments.',
    requirements: [
      'Maintain referential integrity between departments, instructors, students, and courses.',
      'Compute aggregate student enrollment statistics per department.',
      'Generate semester dean honor roll lists based on GPA thresholds (GPA >= 3.80).',
      'Identify courses with high credit loads and analyze faculty teaching distribution.',
    ],
    databaseId: 'university_db',
    skillsLearned: ['Schema Modeling', 'Relational JOINs', 'Aggregations', 'Subqueries', 'Integrity Constraints'],
    xpReward: 100,
    tasks: [
      {
        id: 't_1_1',
        title: 'Task 1: Department Enrollment Census',
        description: 'Query all department names, total student count enrolled in that department, and average student GPA rounded to 2 decimal places. Order by student count descending.',
        databaseId: 'university_db',
        initialSql: `SELECT 
    d.dept_name,
    COUNT(s.student_id) AS student_count,
    ROUND(AVG(s.gpa), 2) AS avg_gpa
FROM departments d
LEFT JOIN students s ON d.dept_id = s.dept_id
GROUP BY d.dept_name
ORDER BY student_count DESC;`,
        solutionQuery: `SELECT d.dept_name, COUNT(s.student_id) AS student_count, ROUND(AVG(s.gpa), 2) AS avg_gpa FROM departments d LEFT JOIN students s ON d.dept_id = s.dept_id GROUP BY d.dept_name ORDER BY student_count DESC;`,
        hints: ['Use LEFT JOIN between departments and students to ensure departments with 0 students are counted.', 'Group by d.dept_name.'],
        xpReward: 25,
      },
      {
        id: 't_1_2',
        title: 'Task 2: Faculty Compensation Analysis',
        description: 'Find the top 3 highest-earning faculty members. Display their name, department name, building location, and salary.',
        databaseId: 'university_db',
        initialSql: `SELECT 
    i.name AS instructor_name,
    d.dept_name,
    d.building,
    i.salary
FROM instructors i
JOIN departments d ON i.dept_id = d.dept_id
ORDER BY i.salary DESC
LIMIT 3;`,
        solutionQuery: `SELECT i.name AS instructor_name, d.dept_name, d.building, i.salary FROM instructors i JOIN departments d ON i.dept_id = d.dept_id ORDER BY i.salary DESC LIMIT 3;`,
        hints: ['Join instructors and departments on dept_id.', 'Order by salary DESC and limit to 3.'],
        xpReward: 25,
      },
    ],
  },
  {
    id: 'proj_2',
    title: 'E-Commerce Retail Analytics & Customer Lifetime Value',
    category: 'Retail',
    difficulty: 'Medium',
    estimatedHours: 5,
    problemStatement: 'Analyze online storefront transactions, product inventory turnover, customer repurchase behavior, and order item breakdowns.',
    requirements: [
      'Track order status from Pending to Delivered.',
      'Compute line item totals and gross revenue contributions per category.',
      'Detect high-value recurring customers and inactive accounts.',
    ],
    databaseId: 'ecommerce_db',
    skillsLearned: ['Revenue Modeling', 'Multi-table JOINs', 'GROUP BY Aggregations', 'Window Functions'],
    xpReward: 120,
    tasks: [
      {
        id: 't_2_1',
        title: 'Task 1: Category Revenue Breakdown',
        description: 'Calculate total revenue generated by each product category. Display category name and total sales as `category_revenue`. Order by revenue descending.',
        databaseId: 'ecommerce_db',
        initialSql: `SELECT 
    c.category_name,
    SUM(oi.quantity * oi.unit_price) AS category_revenue
FROM categories c
JOIN products p ON c.category_id = p.category_id
JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY c.category_name
ORDER BY category_revenue DESC;`,
        solutionQuery: `SELECT c.category_name, SUM(oi.quantity * oi.unit_price) AS category_revenue FROM categories c JOIN products p ON c.category_id = p.category_id JOIN order_items oi ON p.product_id = oi.product_id GROUP BY c.category_name ORDER BY category_revenue DESC;`,
        hints: ['Join categories -> products -> order_items.', 'Multiply quantity * unit_price and sum.'],
        xpReward: 30,
      },
    ],
  },
  {
    id: 'proj_3',
    title: 'FinTech Banking & Transaction Ledger System',
    category: 'Finance',
    difficulty: 'Hard',
    estimatedHours: 6,
    problemStatement: 'Model a modern banking core engine with checking and savings accounts, debit/credit transaction ledger entries, and customer creditworthiness scoring.',
    requirements: [
      'Maintain double-entry ledger debit and credit records.',
      'Audit accounts with balances exceeding customer average thresholds.',
      'Ensure atomicity and consistency of financial ledger logs.',
    ],
    databaseId: 'banking_db',
    skillsLearned: ['Financial Ledgers', 'Transaction Isolation', 'Subqueries', 'Analytical Window Functions'],
    xpReward: 150,
    tasks: [
      {
        id: 't_3_1',
        title: 'Task 1: Account Portfolio Summary',
        description: 'For each customer, calculate their total balance summed across all active accounts. Display customer full name, credit score, and total balance as `total_portfolio_balance`.',
        databaseId: 'banking_db',
        initialSql: `SELECT 
    c.full_name,
    c.credit_score,
    SUM(a.balance) AS total_portfolio_balance
FROM customers c
JOIN accounts a ON c.cust_id = a.cust_id
WHERE a.status = 'Active'
GROUP BY c.cust_id, c.full_name, c.credit_score
ORDER BY total_portfolio_balance DESC;`,
        solutionQuery: `SELECT c.full_name, c.credit_score, SUM(a.balance) AS total_portfolio_balance FROM customers c JOIN accounts a ON c.cust_id = a.cust_id WHERE a.status = 'Active' GROUP BY c.cust_id, c.full_name, c.credit_score ORDER BY total_portfolio_balance DESC;`,
        hints: ['Join customers and accounts on cust_id.', 'Filter by status = "Active".', 'Group by customer and sum balance.'],
        xpReward: 35,
      },
    ],
  },
  {
    id: 'proj_4',
    title: 'Hospital Clinical Patient & Appointment Management',
    category: 'Healthcare',
    difficulty: 'Medium',
    estimatedHours: 4,
    problemStatement: 'Manage physician schedules, patient clinical charts, specialist consultation fees, and appointment records.',
    requirements: [
      'Track physician specializations and doctor consultation revenue.',
      'Manage patient demographics and blood group compatibility.',
      'Analyze recurring medical consultation trends.',
    ],
    databaseId: 'hospital_db',
    skillsLearned: ['Healthcare Schema', 'Relational Queries', 'Aggregations', 'JOINs'],
    xpReward: 100,
    tasks: [
      {
        id: 't_4_1',
        title: 'Task 1: Physician Consultation Volume',
        description: 'Calculate the total number of consultations and gross fees earned by each doctor. Display doctor name, specialization, appointment count (as `total_consultations`), and total revenue (as `gross_revenue`).',
        databaseId: 'hospital_db',
        initialSql: `SELECT 
    d.doctor_name,
    d.specialization,
    COUNT(a.appointment_id) AS total_consultations,
    SUM(a.fee) AS gross_revenue
FROM doctors d
LEFT JOIN appointments a ON d.doctor_id = a.doctor_id
GROUP BY d.doctor_id, d.doctor_name, d.specialization
ORDER BY gross_revenue DESC;`,
        solutionQuery: `SELECT d.doctor_name, d.specialization, COUNT(a.appointment_id) AS total_consultations, SUM(a.fee) AS gross_revenue FROM doctors d LEFT JOIN appointments a ON d.doctor_id = a.doctor_id GROUP BY d.doctor_id, d.doctor_name, d.specialization ORDER BY gross_revenue DESC;`,
        hints: ['Use LEFT JOIN between doctors and appointments.', 'Group by doctor and aggregate fees.'],
        xpReward: 30,
      },
    ],
  },
];
